/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ivzeexlgihrmlnolvolv"
// Provide the publishable key for frontend usage
export const publicAnonKey = "sb_publishable_Fdk75F2Cko0Baije4u7Ifg_OAh-wXsB"
// Secret key should not be exposed here, but for reference: sb_secret_HN6WB ...