/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

<<<<<<< HEAD
export const projectId = "ivzeexlgihrmlnolvolv"
// Provide the publishable key for frontend usage
export const publicAnonKey = "sb_publishable_Fdk75F2Cko0Baije4u7Ifg_OAh-wXsB"
// Secret key should not be exposed here, but for reference: sb_secret_HN6WB ...
=======
export const projectId = "vvpzdkgbbxguukqtvvwd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2cHpka2diYnhndXVrcXR2dndkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxNDA0ODcsImV4cCI6MjA4MjcxNjQ4N30.dbpNq-nHpIR8XyCzGMZYkfACn51XprvLb18wlhiq2_I"
>>>>>>> 51711f9e812bcbd7f4fae318a162b88a401f618e
